
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSDIVIDE EQUAL LPAREN MINUS NAME NUMBER PLUS RPAREN SEMICOLON TIMESstatement : statement expression SEMICOLON\n                 | expression SEMICOLONexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expression\n                  | expression EQUAL expressionexpression : MINUS expression %prec UMINUSexpression : LPAREN expression RPARENexpression : NUMBERexpression : NAMEstatement : NAME EQUAL expression SEMICOLON'
    
_lr_action_items = {'NAME':([0,1,4,5,9,10,11,12,13,14,15,18,26,],[3,8,8,8,-2,8,8,8,8,8,8,-1,-12,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,],[4,4,11,-11,4,4,-10,11,-11,-2,4,4,4,4,4,4,-8,11,-1,-3,-4,-5,-6,11,11,-9,-12,]),'LPAREN':([0,1,4,5,9,10,11,12,13,14,15,18,26,],[5,5,5,5,-2,5,5,5,5,5,5,-1,-12,]),'NUMBER':([0,1,4,5,9,10,11,12,13,14,15,18,26,],[6,6,6,6,-2,6,6,6,6,6,6,-1,-12,]),'$end':([1,9,18,26,],[0,-2,-1,-12,]),'SEMICOLON':([2,3,6,7,8,16,19,20,21,22,23,24,25,],[9,-11,-10,18,-11,-8,-3,-4,-5,-6,-7,26,-9,]),'PLUS':([2,3,6,7,8,16,17,19,20,21,22,23,24,25,],[10,-11,-10,10,-11,-8,10,-3,-4,-5,-6,10,10,-9,]),'TIMES':([2,3,6,7,8,16,17,19,20,21,22,23,24,25,],[12,-11,-10,12,-11,-8,12,12,12,-5,-6,12,12,-9,]),'DIVIDE':([2,3,6,7,8,16,17,19,20,21,22,23,24,25,],[13,-11,-10,13,-11,-8,13,13,13,-5,-6,13,13,-9,]),'EQUAL':([2,3,6,7,8,16,17,19,20,21,22,23,24,25,],[14,15,-10,14,-11,-8,14,-3,-4,-5,-6,14,14,-9,]),'RPAREN':([6,8,16,17,19,20,21,22,23,25,],[-10,-11,-8,25,-3,-4,-5,-6,-7,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,1,4,5,10,11,12,13,14,15,],[2,7,16,17,19,20,21,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> statement expression SEMICOLON','statement',3,'p_statement_expr','calc1.py',55),
  ('statement -> expression SEMICOLON','statement',2,'p_statement_expr','calc1.py',56),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','calc1.py',65),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','calc1.py',66),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','calc1.py',67),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','calc1.py',68),
  ('expression -> expression EQUAL expression','expression',3,'p_expression_binop','calc1.py',69),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','calc1.py',79),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','calc1.py',83),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc1.py',87),
  ('expression -> NAME','expression',1,'p_expression_name','calc1.py',91),
  ('statement -> NAME EQUAL expression SEMICOLON','statement',4,'p_expression_affect','calc1.py',99),
]
